#!/usr/bin/env python3
"""
Tunnel Crack Detection GUI
==========================
A professional desktop GUI for classifying tunnel / concrete-surface images as
'crack' or 'non_crack' using OpenAI's vision-capable language models (VLMs).

Features
--------
- Single-image classification with live JSON parsing and image preview
- Batch processing over a labeled folder (sub-dirs: crack/ and non_crack/)
- Per-image metrics: inference time, input/output/total tokens
- Aggregate metrics: accuracy, precision, recall (sensitivity), specificity,
  F1, F2, ROC-AUC, PR-AUC, MCC, confusion matrix
- Live confusion-matrix, ROC, and Precision-Recall curve plots
- Adjustable decision threshold that recomputes metrics on the fly
- CSV export of per-image results, JSON export of the aggregated report
- Multi-model support — choose any OpenAI vision-capable model
- Threaded API calls (UI stays responsive) with a Cancel button

Dependencies
------------
    pip install openai pillow numpy scikit-learn matplotlib

Run
---
    python tunnel_crack_gui.py

Author: generated by Claude
License: MIT
"""

from __future__ import annotations

import base64
import csv
import json
import os
import queue
import threading
import time
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

import tkinter as tk
from tkinter import filedialog, messagebox, ttk

# ---- third-party imports (fail loud on missing deps) ------------------------
try:
    from PIL import Image, ImageTk
except ImportError as e:  # pragma: no cover
    raise SystemExit("Pillow is required.  Install with:  pip install pillow") from e

try:
    import numpy as np
except ImportError as e:  # pragma: no cover
    raise SystemExit("NumPy is required.  Install with:  pip install numpy") from e

try:
    from sklearn.metrics import (
        accuracy_score,
        average_precision_score,
        confusion_matrix,
        fbeta_score,
        matthews_corrcoef,
        precision_recall_curve,
        precision_score,
        recall_score,
        roc_auc_score,
        roc_curve,
    )
except ImportError as e:  # pragma: no cover
    raise SystemExit("scikit-learn is required.  Install with:  pip install scikit-learn") from e

try:
    import matplotlib
    matplotlib.use("TkAgg")
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
    from matplotlib.figure import Figure
except ImportError as e:  # pragma: no cover
    raise SystemExit("matplotlib is required.  Install with:  pip install matplotlib") from e

try:
    from openai import OpenAI
except ImportError as e:  # pragma: no cover
    raise SystemExit("openai is required.  Install with:  pip install openai") from e


# ============================================================================
# Constants
# ============================================================================

APP_TITLE = "Tunnel Crack Detector  -  OpenAI VLM Inspector"
APP_VERSION = "1.0"

DEFAULT_SYSTEM_PROMPT = """You are an expert civil infrastructure inspection assistant specializing in tunnel lining and concrete surface crack detection.
Your task is to analyze the provided tunnel structure image and classify it into one of two classes:
1. crack
2. non_crack

Class definitions:
- crack: A visible physical crack, fracture, split, rupture, discontinuity, or crack-like defect on the tunnel lining, concrete surface, wall, roof, or structural element. Cracks may appear as thin, dark, irregular, linear, curved, branching, or jagged patterns. They may be horizontal, vertical, diagonal, random, or web-like.
- non_crack: No clear crack. Surface texture, shadows, stains, dirt, water marks, construction joints, tile boundaries, lighting variation, cables, marks, edges, rough concrete texture, or image noise should be classified as non_crack unless they clearly represent a physical crack.

Decision rules:
- Use only the visual evidence in the image.
- Do not assume a crack exists unless there is visible crack-like evidence.
- Be safety-aware: if a real crack-like structural discontinuity is visible, classify it as crack.
- Do not confuse shadows, stains, seams, joints, or surface texture with cracks.
- If the image is unclear, still provide the best classification and reflect uncertainty in the probability and confidence values.

Return ONLY valid JSON with these exact fields and nothing else:
{
  "label": "crack" or "non_crack",
  "probability_crack": number between 0 and 1,
  "confidence": number between 0 and 1,
  "explanation": "brief visual reason for the decision"
}

Probability guidance:
- probability_crack close to 1.0 means the image very likely contains a crack.
- probability_crack close to 0.0 means the image very likely does not contain a crack.
- probability_crack around 0.5 means the image is ambiguous.
- The label should be 'crack' when probability_crack >= threshold (default 0.5).
- The label should be 'non_crack' when probability_crack < threshold."""

DEFAULT_USER_PROMPT = (
    "Classify this tunnel / concrete surface image. "
    "Return only the JSON object as specified, with no Markdown fences or extra commentary."
)

DEFAULT_MODELS = [
    "gpt-4o",
    "gpt-4o-mini",
    "gpt-4.1",
    "gpt-4.1-mini",
    "gpt-4.1-nano",
    "gpt-4-turbo",
    "o4-mini",
    "o3",
]

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tif", ".tiff"}

# Class encoding: positive class = crack
LABEL_CRACK = 1
LABEL_NON_CRACK = 0
LABEL_NAMES = {LABEL_CRACK: "crack", LABEL_NON_CRACK: "non_crack"}


# ============================================================================
# Data structures
# ============================================================================

@dataclass
class PredictionResult:
    """Per-image classification result."""
    image_path: str
    true_label: Optional[int]          # 1 / 0 / None
    predicted_label: Optional[int]     # 1 / 0 / None
    probability_crack: Optional[float]
    confidence: Optional[float]
    explanation: str
    raw_response: str
    model: str
    inference_time_s: float
    input_tokens: int
    output_tokens: int
    total_tokens: int
    error: str = ""

    @property
    def true_label_name(self) -> str:
        return LABEL_NAMES.get(self.true_label, "unknown") if self.true_label is not None else "—"

    @property
    def pred_label_name(self) -> str:
        return LABEL_NAMES.get(self.predicted_label, "unknown") if self.predicted_label is not None else "—"


# ============================================================================
# OpenAI helpers
# ============================================================================

def encode_image_to_data_url(path: str) -> str:
    """Read an image from disk and return a base64 data URL."""
    ext = Path(path).suffix.lower().lstrip(".")
    mime_subtype = "jpeg" if ext in {"jpg", "jpeg"} else (ext or "png")
    with open(path, "rb") as f:
        b64 = base64.b64encode(f.read()).decode("utf-8")
    return f"data:image/{mime_subtype};base64,{b64}"


def _safe_extract_json(text: str) -> dict:
    """Best-effort JSON extraction from a model response."""
    if not text:
        return {}
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    # Strip ``` fences
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.strip("`")
        if cleaned.lower().startswith("json"):
            cleaned = cleaned[4:]
        try:
            return json.loads(cleaned)
        except json.JSONDecodeError:
            pass
    # Substring between first { and last }
    s, e = text.find("{"), text.rfind("}")
    if s != -1 and e != -1 and e > s:
        try:
            return json.loads(text[s:e + 1])
        except json.JSONDecodeError:
            return {}
    return {}


def classify_image(
    client: OpenAI,
    model: str,
    image_path: str,
    system_prompt: str,
    user_prompt: str,
    request_json_mode: bool = True,
) -> tuple[dict, dict]:
    """Call the OpenAI Vision API.  Returns (parsed_json, meta)."""
    data_url = encode_image_to_data_url(image_path)
    start = time.perf_counter()

    kwargs = dict(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": user_prompt},
                    {"type": "image_url", "image_url": {"url": data_url}},
                ],
            },
        ],
    )
    if request_json_mode:
        kwargs["response_format"] = {"type": "json_object"}

    try:
        response = client.chat.completions.create(**kwargs)
    except TypeError:
        # Some reasoning models do not accept response_format — retry without it
        kwargs.pop("response_format", None)
        response = client.chat.completions.create(**kwargs)

    elapsed = time.perf_counter() - start

    raw = response.choices[0].message.content or ""
    usage = getattr(response, "usage", None)
    meta = {
        "elapsed": elapsed,
        "input_tokens": int(getattr(usage, "prompt_tokens", 0) or 0),
        "output_tokens": int(getattr(usage, "completion_tokens", 0) or 0),
        "total_tokens": int(getattr(usage, "total_tokens", 0) or 0),
        "raw": raw,
    }
    return _safe_extract_json(raw), meta


# ============================================================================
# Metrics computation
# ============================================================================

def compute_metrics(results: list[PredictionResult], threshold: float = 0.5) -> dict:
    """Compute aggregate metrics from a list of PredictionResult."""
    valid = [r for r in results if r.true_label is not None and r.probability_crack is not None and not r.error]
    if not valid:
        return {"n_valid": 0}

    y_true = np.array([r.true_label for r in valid], dtype=int)
    y_prob = np.array([r.probability_crack for r in valid], dtype=float)
    y_pred = (y_prob >= threshold).astype(int)

    out: dict = {
        "n_valid": len(valid),
        "n_total": len(results),
        "threshold": threshold,
        "accuracy": float(accuracy_score(y_true, y_pred)),
    }

    # Need both classes present for some metrics
    both_classes_true = len(set(y_true.tolist())) == 2
    both_classes_pred = len(set(y_pred.tolist())) == 2

    out["precision"] = float(precision_score(y_true, y_pred, zero_division=0))
    out["recall_sensitivity"] = float(recall_score(y_true, y_pred, zero_division=0))
    out["f1"] = float(fbeta_score(y_true, y_pred, beta=1.0, zero_division=0))
    out["f2"] = float(fbeta_score(y_true, y_pred, beta=2.0, zero_division=0))
    out["mcc"] = float(matthews_corrcoef(y_true, y_pred)) if (both_classes_true and both_classes_pred) else 0.0

    # Specificity = TN / (TN + FP)
    cm = confusion_matrix(y_true, y_pred, labels=[LABEL_NON_CRACK, LABEL_CRACK])
    tn, fp, fn, tp = cm.ravel() if cm.size == 4 else (0, 0, 0, 0)
    out["specificity"] = float(tn / (tn + fp)) if (tn + fp) > 0 else 0.0
    out["confusion_matrix"] = cm.tolist()
    out["tp"], out["fp"], out["tn"], out["fn"] = int(tp), int(fp), int(tn), int(fn)

    # AUC metrics need both classes in y_true
    if both_classes_true:
        try:
            out["roc_auc"] = float(roc_auc_score(y_true, y_prob))
        except Exception:
            out["roc_auc"] = float("nan")
        try:
            out["pr_auc"] = float(average_precision_score(y_true, y_prob))
        except Exception:
            out["pr_auc"] = float("nan")
    else:
        out["roc_auc"] = float("nan")
        out["pr_auc"] = float("nan")

    # Token + timing aggregates
    out["total_inference_time_s"] = float(sum(r.inference_time_s for r in valid))
    out["mean_inference_time_s"] = float(np.mean([r.inference_time_s for r in valid]))
    out["total_input_tokens"] = int(sum(r.input_tokens for r in valid))
    out["total_output_tokens"] = int(sum(r.output_tokens for r in valid))
    out["total_tokens"] = int(sum(r.total_tokens for r in valid))

    return out


# ============================================================================
# Main application
# ============================================================================

class TunnelCrackApp(tk.Tk):
    """Top-level Tk application."""

    # ------------------------------------------------------------------ init
    def __init__(self) -> None:
        super().__init__()
        self.title(f"{APP_TITLE}  v{APP_VERSION}")
        self.geometry("1280x820")
        self.minsize(1100, 720)

        # ttk theme
        style = ttk.Style(self)
        for candidate in ("clam", "alt", "default"):
            if candidate in style.theme_names():
                style.theme_use(candidate)
                break
        style.configure("TNotebook.Tab", padding=(14, 8))
        style.configure("Header.TLabel", font=("Segoe UI", 11, "bold"))
        style.configure("Big.TLabel", font=("Segoe UI", 14, "bold"))
        style.configure("Metric.TLabel", font=("Consolas", 10))
        style.configure("Accent.TButton", font=("Segoe UI", 10, "bold"))

        # State variables
        self.api_key_var = tk.StringVar(value=os.environ.get("OPENAI_API_KEY", ""))
        self.base_url_var = tk.StringVar(value="")
        self.model_var = tk.StringVar(value=DEFAULT_MODELS[0])
        self.threshold_var = tk.DoubleVar(value=0.5)
        self.single_image_path: Optional[str] = None
        self.results: list[PredictionResult] = []

        # Threading
        self._worker_thread: Optional[threading.Thread] = None
        self._stop_flag = threading.Event()
        self._queue: queue.Queue = queue.Queue()

        # Build UI
        self._build_ui()
        self.after(120, self._drain_queue)

        # Graceful close
        self.protocol("WM_DELETE_WINDOW", self._on_close)

    # ------------------------------------------------------------------ UI
    def _build_ui(self) -> None:
        # Top banner
        banner = ttk.Frame(self, padding=(12, 8))
        banner.pack(fill="x")
        ttk.Label(banner, text="🛠   Tunnel Crack Detector", style="Big.TLabel").pack(side="left")
        ttk.Label(
            banner,
            text="OpenAI Vision-Language-Model powered concrete inspection",
            foreground="#666",
        ).pack(side="left", padx=12)

        ttk.Separator(self).pack(fill="x")

        # Notebook
        self.nb = ttk.Notebook(self)
        self.nb.pack(fill="both", expand=True, padx=8, pady=8)

        self.tab_config = ttk.Frame(self.nb)
        self.tab_single = ttk.Frame(self.nb)
        self.tab_batch = ttk.Frame(self.nb)
        self.tab_metrics = ttk.Frame(self.nb)

        self.nb.add(self.tab_config, text="⚙   Configuration")
        self.nb.add(self.tab_single, text="🖼   Single Image")
        self.nb.add(self.tab_batch, text="📂   Batch Processing")
        self.nb.add(self.tab_metrics, text="📊   Metrics & Plots")

        self._build_tab_config(self.tab_config)
        self._build_tab_single(self.tab_single)
        self._build_tab_batch(self.tab_batch)
        self._build_tab_metrics(self.tab_metrics)

        # Status bar
        self.status_var = tk.StringVar(value="Ready.")
        bar = ttk.Frame(self, relief="sunken", padding=(8, 4))
        bar.pack(side="bottom", fill="x")
        ttk.Label(bar, textvariable=self.status_var).pack(side="left")
        ttk.Label(bar, text=f"v{APP_VERSION}", foreground="#888").pack(side="right")

    # ---- Tab 1: Configuration ------------------------------------------------
    def _build_tab_config(self, parent: ttk.Frame) -> None:
        frm = ttk.LabelFrame(parent, text="API & Model", padding=12)
        frm.pack(fill="x", padx=12, pady=10)

        # API key
        ttk.Label(frm, text="OpenAI API key:", style="Header.TLabel").grid(row=0, column=0, sticky="w", pady=4)
        self.api_entry = ttk.Entry(frm, textvariable=self.api_key_var, show="•", width=70)
        self.api_entry.grid(row=0, column=1, sticky="we", padx=8, pady=4)
        self._show_key = tk.BooleanVar(value=False)
        ttk.Checkbutton(
            frm, text="Show", variable=self._show_key,
            command=lambda: self.api_entry.configure(show="" if self._show_key.get() else "•"),
        ).grid(row=0, column=2, padx=4)

        # Base URL
        ttk.Label(frm, text="Base URL (optional):", style="Header.TLabel").grid(row=1, column=0, sticky="w", pady=4)
        ttk.Entry(frm, textvariable=self.base_url_var, width=70).grid(row=1, column=1, sticky="we", padx=8, pady=4)
        ttk.Label(frm, text="leave blank for OpenAI default", foreground="#888").grid(row=1, column=2, sticky="w")

        # Model
        ttk.Label(frm, text="VLM model:", style="Header.TLabel").grid(row=2, column=0, sticky="w", pady=4)
        self.model_combo = ttk.Combobox(frm, textvariable=self.model_var, values=DEFAULT_MODELS, width=40)
        self.model_combo.grid(row=2, column=1, sticky="w", padx=8, pady=4)
        ttk.Label(frm, text="(editable — type any vision-capable model)", foreground="#888").grid(
            row=2, column=2, sticky="w")

        # Threshold
        ttk.Label(frm, text="Decision threshold:", style="Header.TLabel").grid(row=3, column=0, sticky="w", pady=4)
        thr_frame = ttk.Frame(frm)
        thr_frame.grid(row=3, column=1, sticky="we", padx=8, pady=4)
        self.threshold_scale = ttk.Scale(
            thr_frame, from_=0.0, to=1.0, orient="horizontal", variable=self.threshold_var,
            command=lambda v: self._on_threshold_changed(),
        )
        self.threshold_scale.pack(side="left", fill="x", expand=True)
        self.threshold_label = ttk.Label(thr_frame, text="0.50", width=6, anchor="e")
        self.threshold_label.pack(side="left", padx=8)

        frm.columnconfigure(1, weight=1)

        # Test connection
        btn_row = ttk.Frame(parent, padding=12)
        btn_row.pack(fill="x")
        ttk.Button(btn_row, text="Test Connection", command=self._test_connection).pack(side="left")
        ttk.Label(btn_row, text="(verifies the API key by listing models)", foreground="#888").pack(side="left", padx=10)

        # Prompts
        prm = ttk.LabelFrame(parent, text="Prompts", padding=12)
        prm.pack(fill="both", expand=True, padx=12, pady=10)

        ttk.Label(prm, text="System prompt:", style="Header.TLabel").pack(anchor="w")
        self.system_prompt_text = tk.Text(prm, height=10, wrap="word", font=("Segoe UI", 9))
        self.system_prompt_text.pack(fill="both", expand=True, pady=4)
        self.system_prompt_text.insert("1.0", DEFAULT_SYSTEM_PROMPT)

        ttk.Label(prm, text="User prompt:", style="Header.TLabel").pack(anchor="w", pady=(8, 0))
        self.user_prompt_text = tk.Text(prm, height=3, wrap="word", font=("Segoe UI", 9))
        self.user_prompt_text.pack(fill="x", pady=4)
        self.user_prompt_text.insert("1.0", DEFAULT_USER_PROMPT)

        actions = ttk.Frame(prm)
        actions.pack(fill="x", pady=4)
        ttk.Button(actions, text="Reset Prompts to Default", command=self._reset_prompts).pack(side="right")

    # ---- Tab 2: Single image -------------------------------------------------
    def _build_tab_single(self, parent: ttk.Frame) -> None:
        # Left = image preview, right = controls + result
        pw = ttk.PanedWindow(parent, orient="horizontal")
        pw.pack(fill="both", expand=True, padx=8, pady=8)

        # Left
        left = ttk.Frame(pw, padding=8)
        pw.add(left, weight=3)
        ttk.Label(left, text="Image preview", style="Header.TLabel").pack(anchor="w")
        self.preview_canvas = tk.Canvas(left, bg="#1e1e1e", highlightthickness=0)
        self.preview_canvas.pack(fill="both", expand=True, pady=4)
        self._preview_imgtk: Optional[ImageTk.PhotoImage] = None
        self.preview_canvas.bind("<Configure>", lambda _e: self._render_preview())

        # Right
        right = ttk.Frame(pw, padding=8)
        pw.add(right, weight=2)

        sel = ttk.LabelFrame(right, text="Image", padding=10)
        sel.pack(fill="x", pady=4)
        self.single_path_var = tk.StringVar(value="(no image selected)")
        ttk.Label(sel, textvariable=self.single_path_var, wraplength=380, foreground="#444").pack(anchor="w", pady=2)
        bts = ttk.Frame(sel)
        bts.pack(fill="x", pady=4)
        ttk.Button(bts, text="Browse image…", command=self._browse_single).pack(side="left")
        ttk.Button(bts, text="Classify", style="Accent.TButton",
                   command=self._classify_single).pack(side="left", padx=8)

        # Result panel
        res = ttk.LabelFrame(right, text="Result", padding=10)
        res.pack(fill="both", expand=True, pady=4)

        self.result_label_var = tk.StringVar(value="—")
        self.result_prob_var = tk.StringVar(value="—")
        self.result_conf_var = tk.StringVar(value="—")
        self.result_time_var = tk.StringVar(value="—")
        self.result_tokens_var = tk.StringVar(value="—")
        self.result_model_var = tk.StringVar(value="—")

        grid_rows = [
            ("Predicted label", self.result_label_var),
            ("probability_crack", self.result_prob_var),
            ("confidence", self.result_conf_var),
            ("Inference time", self.result_time_var),
            ("Token usage (in / out / total)", self.result_tokens_var),
            ("Model", self.result_model_var),
        ]
        for i, (lbl, var) in enumerate(grid_rows):
            ttk.Label(res, text=lbl + ":", style="Header.TLabel").grid(row=i, column=0, sticky="w", padx=2, pady=2)
            ttk.Label(res, textvariable=var, style="Metric.TLabel").grid(row=i, column=1, sticky="w", padx=8, pady=2)
        res.columnconfigure(1, weight=1)

        ttk.Label(res, text="Explanation:", style="Header.TLabel").grid(row=len(grid_rows), column=0, sticky="nw", padx=2, pady=4)
        self.result_expl_text = tk.Text(res, height=4, wrap="word", font=("Segoe UI", 9))
        self.result_expl_text.grid(row=len(grid_rows), column=1, sticky="we", padx=8, pady=4)
        self.result_expl_text.configure(state="disabled")

        ttk.Label(res, text="Raw JSON:", style="Header.TLabel").grid(row=len(grid_rows) + 1, column=0, sticky="nw", padx=2, pady=4)
        self.result_raw_text = tk.Text(res, height=8, wrap="word", font=("Consolas", 9))
        self.result_raw_text.grid(row=len(grid_rows) + 1, column=1, sticky="nwes", padx=8, pady=4)
        self.result_raw_text.configure(state="disabled")
        res.rowconfigure(len(grid_rows) + 1, weight=1)

    # ---- Tab 3: Batch --------------------------------------------------------
    def _build_tab_batch(self, parent: ttk.Frame) -> None:
        top = ttk.LabelFrame(parent, text="Dataset", padding=10)
        top.pack(fill="x", padx=8, pady=8)

        info = (
            "Select a folder containing two subfolders:  crack/   and   non_crack/\n"
            "Each subfolder should hold the corresponding images. "
            "Ground-truth labels are inferred from the subfolder names."
        )
        ttk.Label(top, text=info, foreground="#444", justify="left").pack(anchor="w", pady=2)

        self.dataset_dir_var = tk.StringVar(value="")
        row = ttk.Frame(top)
        row.pack(fill="x", pady=6)
        ttk.Entry(row, textvariable=self.dataset_dir_var).pack(side="left", fill="x", expand=True)
        ttk.Button(row, text="Browse…", command=self._browse_dataset).pack(side="left", padx=6)

        ctrl = ttk.Frame(top)
        ctrl.pack(fill="x", pady=6)
        ttk.Label(ctrl, text="Limit per class (0 = all):").pack(side="left")
        self.limit_var = tk.IntVar(value=0)
        ttk.Spinbox(ctrl, from_=0, to=10000, textvariable=self.limit_var, width=8).pack(side="left", padx=6)

        ttk.Button(ctrl, text="▶ Start Batch", style="Accent.TButton",
                   command=self._start_batch).pack(side="left", padx=20)
        self.cancel_btn = ttk.Button(ctrl, text="⏹ Cancel", command=self._cancel_batch, state="disabled")
        self.cancel_btn.pack(side="left", padx=4)
        ttk.Button(ctrl, text="Clear results", command=self._clear_results).pack(side="left", padx=12)

        # Progress
        prog = ttk.Frame(parent, padding=(8, 0))
        prog.pack(fill="x")
        self.progress_var = tk.DoubleVar(value=0)
        self.progress_bar = ttk.Progressbar(prog, variable=self.progress_var, maximum=100)
        self.progress_bar.pack(fill="x", expand=True, side="left", padx=(0, 8))
        self.progress_label_var = tk.StringVar(value="0 / 0")
        ttk.Label(prog, textvariable=self.progress_label_var, width=14, anchor="e").pack(side="left")

        # Results table
        tbl_frame = ttk.LabelFrame(parent, text="Per-image results", padding=6)
        tbl_frame.pack(fill="both", expand=True, padx=8, pady=8)

        cols = ("file", "true", "pred", "prob", "conf", "time", "tokens", "error")
        self.tree = ttk.Treeview(tbl_frame, columns=cols, show="headings", height=14)
        headings = {
            "file": ("File", 320),
            "true": ("True", 80),
            "pred": ("Pred", 80),
            "prob": ("Prob", 70),
            "conf": ("Conf", 70),
            "time": ("Time (s)", 80),
            "tokens": ("Tokens (in/out)", 130),
            "error": ("Error", 220),
        }
        for c, (h, w) in headings.items():
            self.tree.heading(c, text=h)
            self.tree.column(c, width=w, anchor="w")
        vsb = ttk.Scrollbar(tbl_frame, orient="vertical", command=self.tree.yview)
        self.tree.configure(yscrollcommand=vsb.set)
        self.tree.pack(side="left", fill="both", expand=True)
        vsb.pack(side="right", fill="y")

        # Export
        exp = ttk.Frame(parent, padding=(8, 4))
        exp.pack(fill="x")
        ttk.Button(exp, text="💾 Export results CSV", command=self._export_csv).pack(side="left")
        ttk.Button(exp, text="💾 Export metrics report (JSON)", command=self._export_metrics).pack(side="left", padx=8)

    # ---- Tab 4: Metrics ------------------------------------------------------
    def _build_tab_metrics(self, parent: ttk.Frame) -> None:
        # Left: metrics text; right: 3 plots
        pw = ttk.PanedWindow(parent, orient="horizontal")
        pw.pack(fill="both", expand=True, padx=8, pady=8)

        left = ttk.Frame(pw, padding=10)
        pw.add(left, weight=1)

        ttk.Label(left, text="Aggregate Metrics", style="Big.TLabel").pack(anchor="w")
        ttk.Label(left, text="(re-computed live when the threshold changes)",
                  foreground="#888").pack(anchor="w", pady=(0, 8))

        self.metrics_text = tk.Text(left, width=42, height=30, font=("Consolas", 10), wrap="word")
        self.metrics_text.pack(fill="both", expand=True)
        self.metrics_text.configure(state="disabled")

        ttk.Button(left, text="🔄 Refresh", command=self._refresh_metrics_tab).pack(pady=8, anchor="w")

        # Right: figure
        right = ttk.Frame(pw, padding=4)
        pw.add(right, weight=3)

        self.fig = Figure(figsize=(8.5, 7.0), dpi=100, tight_layout=True)
        self.ax_cm = self.fig.add_subplot(2, 2, 1)
        self.ax_roc = self.fig.add_subplot(2, 2, 2)
        self.ax_pr = self.fig.add_subplot(2, 2, 3)
        self.ax_hist = self.fig.add_subplot(2, 2, 4)
        for ax, title in (
            (self.ax_cm, "Confusion matrix"),
            (self.ax_roc, "ROC curve"),
            (self.ax_pr, "Precision–Recall"),
            (self.ax_hist, "Probability distribution"),
        ):
            ax.set_title(title, fontsize=10)
            ax.tick_params(labelsize=8)

        self.canvas = FigureCanvasTkAgg(self.fig, master=right)
        self.canvas.draw()
        self.canvas.get_tk_widget().pack(fill="both", expand=True)

    # ================================================================ events
    def _on_threshold_changed(self) -> None:
        thr = self.threshold_var.get()
        self.threshold_label.config(text=f"{thr:.2f}")
        if self.results:
            self._refresh_metrics_tab()

    def _reset_prompts(self) -> None:
        self.system_prompt_text.delete("1.0", "end")
        self.system_prompt_text.insert("1.0", DEFAULT_SYSTEM_PROMPT)
        self.user_prompt_text.delete("1.0", "end")
        self.user_prompt_text.insert("1.0", DEFAULT_USER_PROMPT)

    # ---- API helpers ---------------------------------------------------------
    def _make_client(self) -> Optional[OpenAI]:
        key = self.api_key_var.get().strip()
        if not key:
            messagebox.showerror("Missing key", "Please enter your OpenAI API key on the Configuration tab.")
            return None
        kwargs = {"api_key": key}
        base = self.base_url_var.get().strip()
        if base:
            kwargs["base_url"] = base
        try:
            return OpenAI(**kwargs)
        except Exception as e:
            messagebox.showerror("OpenAI client error", str(e))
            return None

    def _test_connection(self) -> None:
        client = self._make_client()
        if client is None:
            return
        self.status_var.set("Testing connection…")
        try:
            models = client.models.list()
            n = len(list(models))
            self.status_var.set(f"OK — {n} models available.")
            messagebox.showinfo("Connection OK", f"Successfully connected.\n{n} models visible to this key.")
        except Exception as e:
            self.status_var.set("Connection failed.")
            messagebox.showerror("Connection failed", str(e))

    # ---- Single image --------------------------------------------------------
    def _browse_single(self) -> None:
        path = filedialog.askopenfilename(
            title="Select image",
            filetypes=[("Images", " ".join(f"*{e}" for e in IMAGE_EXTS)), ("All files", "*.*")],
        )
        if not path:
            return
        self.single_image_path = path
        self.single_path_var.set(path)
        self._render_preview()

    def _render_preview(self) -> None:
        if not self.single_image_path:
            return
        try:
            img = Image.open(self.single_image_path)
        except Exception as e:
            self.status_var.set(f"Cannot open image: {e}")
            return
        cw = max(self.preview_canvas.winfo_width(), 10)
        ch = max(self.preview_canvas.winfo_height(), 10)
        img.thumbnail((cw - 10, ch - 10))
        self._preview_imgtk = ImageTk.PhotoImage(img)
        self.preview_canvas.delete("all")
        self.preview_canvas.create_image(cw // 2, ch // 2, image=self._preview_imgtk, anchor="center")

    def _classify_single(self) -> None:
        if not self.single_image_path:
            messagebox.showinfo("No image", "Please choose an image first.")
            return
        client = self._make_client()
        if client is None:
            return

        model = self.model_var.get().strip()
        sys_p = self.system_prompt_text.get("1.0", "end").strip()
        usr_p = self.user_prompt_text.get("1.0", "end").strip()
        thr = self.threshold_var.get()

        self.status_var.set(f"Classifying with {model}…")
        self.update_idletasks()

        # run in a thread so the UI does not freeze
        def worker():
            try:
                parsed, meta = classify_image(client, model, self.single_image_path, sys_p, usr_p)
            except Exception as e:
                self._queue.put(("single_error", str(e)))
                return
            self._queue.put(("single_done", (parsed, meta, model, thr)))

        threading.Thread(target=worker, daemon=True).start()

    def _show_single_result(self, parsed: dict, meta: dict, model: str, thr: float) -> None:
        prob = parsed.get("probability_crack")
        conf = parsed.get("confidence")
        label = parsed.get("label")
        expl = parsed.get("explanation", "")

        # If model didn't return a label, derive from probability
        if label not in ("crack", "non_crack") and isinstance(prob, (int, float)):
            label = "crack" if float(prob) >= thr else "non_crack"

        self.result_label_var.set(str(label) if label else "—")
        self.result_prob_var.set(f"{float(prob):.4f}" if isinstance(prob, (int, float)) else "—")
        self.result_conf_var.set(f"{float(conf):.4f}" if isinstance(conf, (int, float)) else "—")
        self.result_time_var.set(f"{meta['elapsed']:.3f} s")
        self.result_tokens_var.set(f"{meta['input_tokens']} / {meta['output_tokens']} / {meta['total_tokens']}")
        self.result_model_var.set(model)

        self.result_expl_text.configure(state="normal")
        self.result_expl_text.delete("1.0", "end")
        self.result_expl_text.insert("1.0", expl)
        self.result_expl_text.configure(state="disabled")

        self.result_raw_text.configure(state="normal")
        self.result_raw_text.delete("1.0", "end")
        try:
            pretty = json.dumps(parsed, indent=2, ensure_ascii=False)
        except Exception:
            pretty = meta.get("raw", "")
        self.result_raw_text.insert("1.0", pretty)
        self.result_raw_text.configure(state="disabled")

        self.status_var.set("Single-image classification complete.")

    # ---- Batch ---------------------------------------------------------------
    def _browse_dataset(self) -> None:
        path = filedialog.askdirectory(title="Select dataset root (containing crack/ and non_crack/)")
        if path:
            self.dataset_dir_var.set(path)

    def _gather_dataset(self, root: str, limit_per_class: int) -> list[tuple[str, int]]:
        root_p = Path(root)
        items: list[tuple[str, int]] = []
        for cls_name, lbl in [("crack", LABEL_CRACK), ("non_crack", LABEL_NON_CRACK)]:
            sub = root_p / cls_name
            if not sub.is_dir():
                continue
            imgs = sorted([p for p in sub.iterdir() if p.suffix.lower() in IMAGE_EXTS])
            if limit_per_class > 0:
                imgs = imgs[:limit_per_class]
            items.extend([(str(p), lbl) for p in imgs])
        return items

    def _start_batch(self) -> None:
        if self._worker_thread and self._worker_thread.is_alive():
            messagebox.showinfo("Busy", "A batch is already running.")
            return
        root = self.dataset_dir_var.get().strip()
        if not root or not Path(root).is_dir():
            messagebox.showerror("Bad path", "Please select a valid dataset folder.")
            return
        client = self._make_client()
        if client is None:
            return

        limit = max(0, int(self.limit_var.get()))
        dataset = self._gather_dataset(root, limit)
        if not dataset:
            messagebox.showerror(
                "No images",
                "No images found.\nExpected sub-folders:\n   <root>/crack/*\n   <root>/non_crack/*",
            )
            return

        model = self.model_var.get().strip()
        sys_p = self.system_prompt_text.get("1.0", "end").strip()
        usr_p = self.user_prompt_text.get("1.0", "end").strip()
        thr = self.threshold_var.get()

        # reset state
        self.results.clear()
        for row in self.tree.get_children():
            self.tree.delete(row)
        self.progress_var.set(0)
        self.progress_label_var.set(f"0 / {len(dataset)}")
        self._stop_flag.clear()
        self.cancel_btn.configure(state="normal")
        self.status_var.set(f"Running batch on {len(dataset)} images with {model}…")
        self.nb.select(self.tab_batch)

        def worker():
            for i, (path, true_lbl) in enumerate(dataset, start=1):
                if self._stop_flag.is_set():
                    self._queue.put(("batch_cancelled", None))
                    return
                rec = PredictionResult(
                    image_path=path, true_label=true_lbl, predicted_label=None,
                    probability_crack=None, confidence=None, explanation="",
                    raw_response="", model=model, inference_time_s=0.0,
                    input_tokens=0, output_tokens=0, total_tokens=0,
                )
                try:
                    parsed, meta = classify_image(client, model, path, sys_p, usr_p)
                    rec.raw_response = meta["raw"]
                    rec.inference_time_s = meta["elapsed"]
                    rec.input_tokens = meta["input_tokens"]
                    rec.output_tokens = meta["output_tokens"]
                    rec.total_tokens = meta["total_tokens"]

                    prob = parsed.get("probability_crack")
                    conf = parsed.get("confidence")
                    label = parsed.get("label")
                    rec.probability_crack = float(prob) if isinstance(prob, (int, float)) else None
                    rec.confidence = float(conf) if isinstance(conf, (int, float)) else None
                    rec.explanation = str(parsed.get("explanation", ""))[:500]

                    if label == "crack":
                        rec.predicted_label = LABEL_CRACK
                    elif label == "non_crack":
                        rec.predicted_label = LABEL_NON_CRACK
                    elif rec.probability_crack is not None:
                        rec.predicted_label = LABEL_CRACK if rec.probability_crack >= thr else LABEL_NON_CRACK
                    else:
                        rec.error = "missing label & probability"
                except Exception as e:
                    rec.error = str(e)[:300]
                self._queue.put(("batch_item", (i, len(dataset), rec)))
            self._queue.put(("batch_done", None))

        self._worker_thread = threading.Thread(target=worker, daemon=True)
        self._worker_thread.start()

    def _cancel_batch(self) -> None:
        if self._worker_thread and self._worker_thread.is_alive():
            self._stop_flag.set()
            self.status_var.set("Cancelling…")

    def _append_result_row(self, i: int, total: int, rec: PredictionResult) -> None:
        self.results.append(rec)
        self.tree.insert("", "end", values=(
            Path(rec.image_path).name,
            rec.true_label_name,
            rec.pred_label_name,
            f"{rec.probability_crack:.3f}" if rec.probability_crack is not None else "—",
            f"{rec.confidence:.3f}" if rec.confidence is not None else "—",
            f"{rec.inference_time_s:.2f}",
            f"{rec.input_tokens}/{rec.output_tokens}",
            rec.error,
        ))
        self.progress_var.set(100.0 * i / total)
        self.progress_label_var.set(f"{i} / {total}")

    def _clear_results(self) -> None:
        if not messagebox.askyesno("Clear results", "Discard all current results?"):
            return
        self.results.clear()
        for row in self.tree.get_children():
            self.tree.delete(row)
        self.progress_var.set(0)
        self.progress_label_var.set("0 / 0")
        self._refresh_metrics_tab()

    # ---- Metrics & plots -----------------------------------------------------
    def _refresh_metrics_tab(self) -> None:
        thr = float(self.threshold_var.get())
        m = compute_metrics(self.results, threshold=thr)

        # ---- text panel ----
        self.metrics_text.configure(state="normal")
        self.metrics_text.delete("1.0", "end")
        if not m or m.get("n_valid", 0) == 0:
            self.metrics_text.insert("end", "No valid results yet.\nRun a batch on a labeled dataset.")
        else:
            lines = [
                f"Threshold            : {m['threshold']:.2f}",
                f"Valid / total        : {m['n_valid']} / {m['n_total']}",
                "",
                "── Classification ──",
                f"Accuracy             : {m['accuracy']:.4f}",
                f"Precision            : {m['precision']:.4f}",
                f"Recall (sensitivity) : {m['recall_sensitivity']:.4f}",
                f"Specificity          : {m['specificity']:.4f}",
                f"F1-score             : {m['f1']:.4f}",
                f"F2-score             : {m['f2']:.4f}",
                f"MCC                  : {m['mcc']:.4f}",
                f"ROC-AUC              : {m['roc_auc']:.4f}" if not np.isnan(m['roc_auc']) else "ROC-AUC              : n/a (single class)",
                f"PR-AUC               : {m['pr_auc']:.4f}" if not np.isnan(m['pr_auc']) else "PR-AUC               : n/a (single class)",
                "",
                "── Confusion matrix (rows = true) ──",
                "                pred=non_crack   pred=crack",
                f"true=non_crack      {m['tn']:>6}        {m['fp']:>6}",
                f"true=crack          {m['fn']:>6}        {m['tp']:>6}",
                "",
                "── Compute ──",
                f"Total inference time : {m['total_inference_time_s']:.2f} s",
                f"Mean per image       : {m['mean_inference_time_s']:.3f} s",
                f"Tokens in / out      : {m['total_input_tokens']} / {m['total_output_tokens']}",
                f"Tokens total         : {m['total_tokens']}",
            ]
            self.metrics_text.insert("end", "\n".join(lines))
        self.metrics_text.configure(state="disabled")

        # ---- plots ----
        self._draw_plots(thr)

    def _draw_plots(self, threshold: float) -> None:
        valid = [r for r in self.results
                 if r.true_label is not None and r.probability_crack is not None and not r.error]

        for ax in (self.ax_cm, self.ax_roc, self.ax_pr, self.ax_hist):
            ax.clear()
        if not valid:
            for ax, title in (
                (self.ax_cm, "Confusion matrix"),
                (self.ax_roc, "ROC curve"),
                (self.ax_pr, "Precision–Recall"),
                (self.ax_hist, "Probability distribution"),
            ):
                ax.set_title(title, fontsize=10)
                ax.text(0.5, 0.5, "no data", ha="center", va="center", transform=ax.transAxes, color="#888")
            self.canvas.draw_idle()
            return

        y_true = np.array([r.true_label for r in valid], dtype=int)
        y_prob = np.array([r.probability_crack for r in valid], dtype=float)
        y_pred = (y_prob >= threshold).astype(int)

        # Confusion matrix
        cm = confusion_matrix(y_true, y_pred, labels=[LABEL_NON_CRACK, LABEL_CRACK])
        self.ax_cm.imshow(cm, cmap="Blues")
        self.ax_cm.set_xticks([0, 1]); self.ax_cm.set_xticklabels(["non_crack", "crack"], fontsize=8)
        self.ax_cm.set_yticks([0, 1]); self.ax_cm.set_yticklabels(["non_crack", "crack"], fontsize=8)
        self.ax_cm.set_xlabel("Predicted", fontsize=9)
        self.ax_cm.set_ylabel("True", fontsize=9)
        self.ax_cm.set_title("Confusion matrix", fontsize=10)
        vmax = cm.max() if cm.size else 1
        for (i, j), v in np.ndenumerate(cm):
            color = "white" if v > vmax / 2 else "black"
            self.ax_cm.text(j, i, str(v), ha="center", va="center", color=color, fontsize=11)

        # ROC
        if len(set(y_true.tolist())) == 2:
            fpr, tpr, _ = roc_curve(y_true, y_prob)
            try:
                auc = roc_auc_score(y_true, y_prob)
            except Exception:
                auc = float("nan")
            self.ax_roc.plot(fpr, tpr, lw=2, label=f"AUC = {auc:.3f}")
            self.ax_roc.plot([0, 1], [0, 1], "--", color="#aaa", lw=1)
            self.ax_roc.set_xlabel("False positive rate", fontsize=9)
            self.ax_roc.set_ylabel("True positive rate", fontsize=9)
            self.ax_roc.set_title("ROC curve", fontsize=10)
            self.ax_roc.legend(loc="lower right", fontsize=8)
            self.ax_roc.grid(alpha=0.3)

            prec, rec, _ = precision_recall_curve(y_true, y_prob)
            try:
                ap = average_precision_score(y_true, y_prob)
            except Exception:
                ap = float("nan")
            self.ax_pr.plot(rec, prec, lw=2, label=f"AP = {ap:.3f}")
            self.ax_pr.set_xlabel("Recall", fontsize=9)
            self.ax_pr.set_ylabel("Precision", fontsize=9)
            self.ax_pr.set_title("Precision–Recall", fontsize=10)
            self.ax_pr.legend(loc="lower left", fontsize=8)
            self.ax_pr.grid(alpha=0.3)
        else:
            self.ax_roc.set_title("ROC curve (need both classes)", fontsize=10)
            self.ax_pr.set_title("Precision–Recall (need both classes)", fontsize=10)

        # Probability histogram
        pos = y_prob[y_true == LABEL_CRACK]
        neg = y_prob[y_true == LABEL_NON_CRACK]
        bins = np.linspace(0, 1, 21)
        if neg.size:
            self.ax_hist.hist(neg, bins=bins, alpha=0.6, label="non_crack", color="#4caf50")
        if pos.size:
            self.ax_hist.hist(pos, bins=bins, alpha=0.6, label="crack", color="#e53935")
        self.ax_hist.axvline(threshold, color="black", linestyle="--", lw=1, label=f"thr={threshold:.2f}")
        self.ax_hist.set_xlabel("probability_crack", fontsize=9)
        self.ax_hist.set_ylabel("count", fontsize=9)
        self.ax_hist.set_title("Probability distribution", fontsize=10)
        self.ax_hist.legend(fontsize=8)
        self.ax_hist.grid(alpha=0.3)

        self.canvas.draw_idle()

    # ---- Exports -------------------------------------------------------------
    def _export_csv(self) -> None:
        if not self.results:
            messagebox.showinfo("Nothing to export", "Run a batch first.")
            return
        path = filedialog.asksaveasfilename(
            defaultextension=".csv",
            initialfile=f"tunnel_crack_results_{datetime.now():%Y%m%d_%H%M%S}.csv",
            filetypes=[("CSV", "*.csv")],
        )
        if not path:
            return
        fields = list(asdict(self.results[0]).keys())
        try:
            with open(path, "w", newline="", encoding="utf-8") as f:
                w = csv.DictWriter(f, fieldnames=fields)
                w.writeheader()
                for r in self.results:
                    w.writerow(asdict(r))
            messagebox.showinfo("Saved", f"Results saved to:\n{path}")
        except Exception as e:
            messagebox.showerror("Save failed", str(e))

    def _export_metrics(self) -> None:
        if not self.results:
            messagebox.showinfo("Nothing to export", "Run a batch first.")
            return
        path = filedialog.asksaveasfilename(
            defaultextension=".json",
            initialfile=f"tunnel_crack_report_{datetime.now():%Y%m%d_%H%M%S}.json",
            filetypes=[("JSON", "*.json")],
        )
        if not path:
            return
        thr = float(self.threshold_var.get())
        m = compute_metrics(self.results, threshold=thr)
        m["model"] = self.model_var.get()
        m["generated_at"] = datetime.now().isoformat(timespec="seconds")
        try:
            with open(path, "w", encoding="utf-8") as f:
                json.dump(m, f, indent=2)
            messagebox.showinfo("Saved", f"Report saved to:\n{path}")
        except Exception as e:
            messagebox.showerror("Save failed", str(e))

    # ---- Queue drain & shutdown ---------------------------------------------
    def _drain_queue(self) -> None:
        try:
            while True:
                kind, payload = self._queue.get_nowait()
                if kind == "single_done":
                    parsed, meta, model, thr = payload
                    self._show_single_result(parsed, meta, model, thr)
                elif kind == "single_error":
                    self.status_var.set("Error.")
                    messagebox.showerror("API error", payload)
                elif kind == "batch_item":
                    i, total, rec = payload
                    self._append_result_row(i, total, rec)
                    if i == total or i % 5 == 0:
                        self._refresh_metrics_tab()
                elif kind == "batch_done":
                    self.cancel_btn.configure(state="disabled")
                    self.status_var.set(f"Batch complete — {len(self.results)} images processed.")
                    self._refresh_metrics_tab()
                    self.nb.select(self.tab_metrics)
                elif kind == "batch_cancelled":
                    self.cancel_btn.configure(state="disabled")
                    self.status_var.set("Batch cancelled.")
                    self._refresh_metrics_tab()
        except queue.Empty:
            pass
        self.after(120, self._drain_queue)

    def _on_close(self) -> None:
        if self._worker_thread and self._worker_thread.is_alive():
            if not messagebox.askyesno("Quit", "A batch is still running.  Quit anyway?"):
                return
            self._stop_flag.set()
        self.destroy()


# ============================================================================
# Entry point
# ============================================================================

def main() -> None:
    app = TunnelCrackApp()
    app.mainloop()


if __name__ == "__main__":
    main()
